### ISSUE TITLE
Compilation Error - LaTeX Error: File `l3bitset.sty' not found.

### ISSUE THREAD

**Issue by nakumah** [John02139/asmeconf#10]
**Describe the bug**

The template fails to compile with the error 
`! LaTeX Error: File `l3bitset.sty' not found.`

My guess is a package is missing, but i cannot find the required package. 
I thought maybe it was the `l3experimental` package, but the compilation still fails even with that installed.

I uploaded the project files to `overleaf` and it compiled successfully.
I do not know why it doesn't work locally.

i have installed the [asmeconf](https://ctan.org/pkg/asmeconf) package from the provided [mirror](https://ctan.mirror.globo.tech)

I am out of ideas, please advice

**Screenshots**
n/a

**Platform (please complete the following information):**
 - OS: Windows 11
 - Distribution: MikTex
 - TeX Program: TexStudio/VS Code

**Additional context**
n/a

**Comment by John02139** [comment]
The missing file not part of the asmeconf package. It is a LaTeX system file (part of the "l3kernel bundle").  So it appears that your local LaTeX installation is missing some files. The most likely reason is that your local installation is out-of-date. You can try updating your LaTeX installation.

If you read the top lines of your .log file, it shows the dates of Latex2e and the L3 programming layer, something like this:

```
LaTeX2e <2024-11-01> patch level 1
L3 programming layer <2024-11-02>
```
Note - don't try dropping in individual system files, just update the whole thing.
