### ISSUE TITLE
June 2022 update of LaTeX kernel produce errors in capitalized captions and headings

### ISSUE THREAD

**Issue by John02139** [John02139/asmeconf#5]
With the June 2022 release of LaTeX, the case-changing commands formerly controlled by the `textcase` package have been absorbed into the kernel, as described in [ltnews35](https://www.latex-project.org/news/latex2e-news/ltnews35.pdf), page 4. There was a bug in this change leading to error messages when certain commands are used in uppercased text, affecting the captions and section headings of `asmeconf`.   The LaTeX Team are now working on a correction that will be distributed in 2022. 

The issue is discussed further at these two links:

https://tex.stackexchange.com/questions/649016/changes-to-textcase-and-latex-kernel-in-the-june-2022-release-affecting-uppercas

https://github.com/latex3/latex2e/issues/881

This bug does **not** affect users who have not rolled forward to the June 2022 release of LaTeX.

**Screenshots**
For example, when running `asmeconf-template.tex`, the following error message will be seen:

<img width="489" alt="Screen Shot 2022-06-30 at 3 19 00 PM" src="https://user-images.githubusercontent.com/39748301/176760292-9fdbf1fa-d92a-4758-a6c4-c480804387c5.png">

**Recommended Work Around**
 Until the LaTeX kernel is updated, users of `asmeconf` can avoid errors as follows:

1. Place `\label{..}` after `\caption{..}`, **not inside** `\caption{..}`. In other words, do `\caption{My caption}\label{My caption label}`
2. Inside captions, do `(\ref{eqn:number})` instead of using `\eqref{eqn:number}`
3. Do not put footnotes inside section headings.

For example, if these changes are made to `asmeconf-template.tex`, the code will run without errors and will produce the expected output.

**Comment by davidcarlisle** [comment]
yes sorry about that , we hope to push out a "PL4" latex update in the next day or so .

**Comment by John02139** [comment]
Thanks, David!  I appreciate your help.

**Comment by davidcarlisle** [comment]
patch level 4 of the June latex release has been sent to ctan so should appear there tomorrow and texlive/miktex mirrors in a few days.

We ended up with a slightly deeper fix than the version I posted to stackexchange, but the same basic issue.

I also added a convenience function `\AddToNoCaseChangeList`  which you can use to make command arguments safe from case chaging so

```
\ifx\AddToNoCaseChangeList\@undefined
% old format, probably \RequirePackage[overload]{textcase}....
\else
% new format
  \AddToNoCaseChangeList{\eqref \footnote \somelocalcommand}
\fi

then

\MakeUppercase{ aaa \eqref{abc} \label{xyz}  bbb \somelocalcommand{www}}
```

should hopefully work, please open an issue in github if not.

**Comment by John02139** [comment]
Latex PL4 has resolved the problems with `\eqref` and `\label`. A new need to protect `\footnote` in section headings (which use the `titlesec` package) is discussed here,  [titlesec](https://github.com/jbezos/titlesec/issues/48 ); `asmeconf.sty` will be patched shortly to work around that issue so that end-users won't need to fuss with it.
