### ISSUE TITLE
Figure and Table Captions should not be bold according to reviewers

### ISSUE THREAD

**Issue by rk-exxec** [John02139/asmeconf#6]
**Describe the bug**
The figure and table captions are made in all caps and bold by the template. However after submission reviewers said, that the captions should not be bold. The provided word template implements this already. (https://www.asme.org/publications-submissions/proceedings/author-guidelines/elements-of-a-paper/author-templates)

**Screenshots**
![grafik](https://github.com/John02139/asmeconf/assets/40037381/e10eade9-d595-4bee-a88a-ea53a0c4668a)

Template output:
![grafik](https://github.com/John02139/asmeconf/assets/40037381/05789726-6451-4cfc-b217-3a3be09dcbbf)

Format as wished by the reviewers:
![grafik](https://github.com/John02139/asmeconf/assets/40037381/80aaffcf-5db4-4dfe-ab8a-841f80196fc2)

Word template:
![grafik](https://github.com/John02139/asmeconf/assets/40037381/fbd0b1d7-8af8-48b5-90d3-823eb7bcc078)

**Platform (please complete the following information):**
 - OS: No os, using Overleaf
 - Distribution: TexLive 2022
 - TeX Program:  Overleaf

**Additional context**
I changed the following lines to achieve the normal font captions:

```latex
\captionsetup[figure]{labelformat=uppercase, labelfont={sf,bf,small},textfont={sf,md,small},textformat=boldmath,labelsep=colon}
\captionsetup[table]{labelformat=uppercase, labelfont={sf,bf,small},textfont={sf,md,small},textformat=boldmath,labelsep=colon,skip=0.5\baselineskip}
```

**Comment by John02139** [comment]
If your reviewers are requesting not to use bold, then it's fine not to use bold.  (Bold captions have been in use for a long time, but different organizers have edited the Word file over the years.)  

You should also delete "textformat=boldmath" to avoid having math in captions render in bold.

You don't need to edit the class file. Just put these two lines in your preamble (after \documentclass[...  and before \begin{document}):

\captionsetup[figure]{labelformat=uppercase, labelfont={sf,bf,small},textfont={sf,md,small},labelsep=colon}

\captionsetup[table]{labelformat=uppercase, labelfont={sf,bf,small},textfont={sf,md,small},labelsep=colon,skip=0.5\baselineskip}

**Comment by rk-exxec** [comment]
I see. Thank you very much!

**Comment by John02139** [comment]
Version 1.35 of asmeconf includes a new class option [unboldcaption] that will set caption text to normal sans serif (not bold). Labels will remain in boldface.  This version should appear in the CTAN mirror sites within a few days.
