### ISSUE TITLE
Package hyperxmp Error

### ISSUE THREAD

**Issue by aq18507** [John02139/asmeconf#7]
**Describe the bug**
When compiling I get the error: "Package hyperxmp Error: hyperref must be loaded before hyperxmp. }", which seems to be caused by the sequence in which the packages `hyperref` `hyperxmp`. There are workarounds suggested online but when implemented they throw new errors. Interestingly this error does not exist on Overleaf, which suggests that this is caused by a different version of the some packages.

**Screenshots**
![image](https://github.com/John02139/asmeconf/assets/91566934/e915cf15-094d-470e-b8f8-90ed80c0acdc)

**Platform (please complete the following information):**
 - **OS:** Windows 10
 - **Distribution** MikTex Latest update
 - **TeX Program:** TeXstudio 4.6.3
 -  **hyperref version:** 17/07/23
 - **hyperxmp version:** 22/09/2023

**Additional context**
N/A

**Comment by John02139** [comment]
A recent update to the hyperxmp package (5.12 2023-09-10) has introduced the requirement to load hyperxmp after hyperref. The earlier versions of hyperxmp did not enforce a specific order. This update is likely not in Overleaf's version of TeXLive, given their update cycle (I'd estimate it will appear in Overleaf during summer or fall 2024).

I'll get a fix into CTAN later today.

**Comment by aq18507** [comment]
Fantastic news, thank you very much for this!

**Comment by John02139** [comment]
Also, if you are running an up-to-date latex installation (as you appear to be), the document metadata are better handled by putting these lines before \documentclass[...]{asmeconf}

\DocumentMetadata{%
	pdfstandard=A-3b,% A-2b, A-2u, A-3b, or A-3u
	pdfversion=1.7,
	lang=en-US,
}

and then omitting the pdf-a options from \documentclass.

This change will also IMMEDIATELY resolve the hyperxmp issue you are seeing.

**Comment by aq18507** [comment]
It does indeed! I have just added this to my `.tex` document, and it now compiles without any errors. Thanks so much for this.

**Comment by John02139** [comment]
The update has been posted to CTAN, and it should appear in the mirror sites within a few days.
