### ISSUE TITLE
LaTeX Error: Unknown option '\MyColorOption' for package xcolor.

### ISSUE THREAD

**Issue by rob5ives** [John02139/asmeconf#8]
Cannot compile a document. I get a warning and error thrown by the xcolor package. 

Package xcolor Warning: Package option `hyperref' is obsolete and ignored on input line 266.

C:\Users\rob5i\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\xcolor.sty:266: LaTeX Error: Unknown option '\MyColorOption' for package xcolor.

The line in question in xcolor is: \edef\Gin@driver{\Gin@driver}

**Comment by John02139** [comment]
Thanks for this message.

 Recent updates to LaTeX (fall 2023) cause obsolete options to be flagged (hyperref and fixpdftex specifically). The latter is passed through an engine-dependent option, \MyColorOption, and this causes the error you see.

I'll post a revision today.  Meanwhile you can remove these two lines in the asmeconf.cls file

```
\ifpdftex\def\MyColorOption{fixpdftex}\else\ifluatex\def\MyColorOption{luatex}\else\def\MyColorOption{}\fi\fi
\RequirePackage[hyperref,\MyColorOption,dvipsnames,svgnames,x11names]{xcolor}
```

and replace them with this line

`\RequirePackage[dvipsnames,svgnames,x11names]{xcolor}
`

**Comment by John02139** [comment]
The update is posted and should appear on the mirror sites during the next 24 hours.

[https://ctan.org/pkg/asmeconf ](https://ctan.org/pkg/asmeconf )
